import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar/navbar";
import ModeToggle from "@/components/theme/Themeswitcher";
import { ThemeProvider } from "@/components/theme/Themeprovider";
const fontSans = FontSans({ subsets: ["latin"], variable:"--font-sans", });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('font-sans antialiased flex items-start justify-between', fontSans.variable)}>
        <ThemeProvider 
         attribute="class"
         defaultTheme="system"
         enableSystem
         disableTransitionOnChange
        >
        <nav><Navbar/></nav>
        <main className=" w-full h-full">
          <div className="pl-2 pt-4"><ModeToggle/></div>
          <div className="p-8">{children}</div> 
        </main>
        </ThemeProvider>
      </body>
    </html>
  );
}




